const VI_STOPWORDS = new Set([
    "toi",
    "minh",
    "la",
    "va",
    "voi",
    "nhe",
    "giup",
    "can",
    "muon",
    "tim",
    "xem",
    "hoi",
    "co",
    "nay",
    "kia",
    "cua",
    "de",
    "mot",
    "nhung",
    "loai",
    "nao",
]);

const EN_STOPWORDS = new Set([
    "i",
    "me",
    "my",
    "the",
    "a",
    "an",
    "and",
    "or",
    "for",
    "with",
    "to",
    "of",
    "please",
    "need",
    "want",
    "show",
    "find",
    "looking",
    "search",
    "some",
    "any",
]);

const VI_DOMAIN_KEYWORDS = new Set([
    "meo",
    "cun",
    "thuc",
    "an",
    "hat",
    "pate",
    "sua",
    "tam",
    "do",
    "choi",
    "phu",
    "kien",
    "san",
    "pham",
    "dich",
    "vu",
    "goi",
    "y",
    "de",
    "xuat",
    "dat",
    "lich",
    "quan",
    "ao",
    "rang",
    "mieng",
    "grooming",
    "spa",
    "giam",
    "gia",
    "khuyen",
    "mai",
    "sale",
    "ve sinh",
    "lau",
    "khu mui",
    "cham soc",
]);

const EN_DOMAIN_KEYWORDS = new Set([
    "dog",
    "dogs",
    "cat",
    "cats",
    "food",
    "toy",
    "toys",
    "product",
    "products",
    "service",
    "services",
    "booking",
    "hotel",
    "training",
    "spa",
    "shampoo",
    "snack",
    "accessory",
    "accessories",
    "clothes",
    "grooming",
    "dental",
    "care",
    "oral",
    "kibble",
    "pate",
    "discount",
    "sale",
    "deal",
    "promotion",
    "milk",
    "wet",
]);

const PET_TYPE_PATTERNS = {
    dog: [
        "cho con",
        "cun",
        "cun con",
        "dog",
        "dogs",
        "puppy",
        "puppies",
        "dog food",
        "dog snack",
        "dog toy",
        "thuc an cho cho",
        "do an cho cho",
        "san pham cho cho",
        "phu kien cho cho",
        "pate cho cho",
        "sua cho cho",
        "do choi cho cho",
        "toy cho cho",
        "cho moc rang",
        "cho dang moc rang",
        "do choi phu hop cho cho",
        "do choi cho cho nho",
    ],
    cat: [
        "meo",
        "meo con",
        "boss",
        "cat",
        "cats",
        "kitten",
        "kittens",
        "cat food",
        "cat snack",
        "cat toy",
        "thuc an cho meo",
        "do an cho meo",
        "san pham cho meo",
        "phu kien cho meo",
        "pate cho meo",
        "sua cho meo",
        "do choi cho meo",
        "toy cho meo",
        "meo ken an",
    ],
};

const PET_SIZE_KEYWORDS = {
    small: ["nho", "mini", "be", "size s", "small", "tiny"],
    medium: ["vua", "size m", "medium"],
    large: ["lon", "size l", "large", "big"],
};

const PRODUCT_FORM_KEYWORDS = {
    pate: [
        "pate",
        "wet food",
        "cat pate",
        "dog pate",
        "pate cho meo",
        "pate cho cho",
    ],
    kibble: ["hat", "kibble", "dry food", "hat cho meo", "hat cho cho"],
    milk: [
        "sua",
        "milk",
        "kitten milk",
        "puppy milk",
        "sua cho meo",
        "sua cho cho",
    ],
    toy: ["do choi", "toy", "toys", "cat toy", "dog toy"],
    snack: ["snack", "treat", "treats", "banh thuong", "thuong"],
    shampoo: [
        "sua tam",
        "shampoo",
        "bath",
        "cleaning",
        "lam sach",
        "ve sinh",
        "khu mui",
        "lau",
        "wipes",
        "cleaning wipes",
    ],
};

const DISCOUNT_KEYWORDS = [
    "giam gia",
    "khuyen mai",
    "sale",
    "dang sale",
    "uu dai",
    "gia tot",
    "discount",
    "discounted",
    "deal",
    "promotion",
    "promo",
];

const NON_DISCOUNT_KEYWORDS = [
    "khong giam gia",
    "khong sale",
    "khong khuyen mai",
    "khong uu dai",
    "gia goc",
    "nguyen gia",
    "full price",
    "not discounted",
    "without discount",
    "non discount",
    "non discounted",
];

const DOMAIN_SYNONYMS = {
    "san pham cho cho": ["dog products", "dog accessories", "phu kien cho cho"],
    "san pham cho meo": ["cat products", "cat accessories", "phu kien cho meo"],
    "phu kien cho cho": ["dog accessories", "dog products"],
    "phu kien cho meo": ["cat accessories", "cat products"],
    "thuc an": ["food", "kibble", "meal", "nutrition"],
    "thuc an cho meo": [
        "cat food",
        "kitten food",
        "pate cho meo",
        "hat cho meo",
    ],
    "thuc an cho cho": [
        "dog food",
        "puppy food",
        "pate cho cho",
        "hat cho cho",
    ],
    "do an cho meo": ["cat food", "snack cho meo", "pate cho meo"],
    "do an cho cho": ["dog food", "snack cho cho", "pate cho cho"],
    "hat cho meo": ["cat food", "kibble", "thuc an cho meo"],
    "hat cho cho": ["dog food", "kibble", "thuc an cho cho"],
    "pate cho meo": ["cat food", "wet food", "thuc an cho meo"],
    "pate cho cho": ["dog food", "wet food", "thuc an cho cho"],
    "sua cho meo": ["kitten milk", "cat milk", "meo con"],
    "sua cho cho": ["puppy milk", "dog milk", "cho con"],

    food: ["thuc an", "hat", "pate", "snack"],
    "cat food": ["thuc an cho meo", "hat cho meo", "pate cho meo"],
    "dog food": ["thuc an cho cho", "hat cho cho", "pate cho cho"],

    "do choi cho cho": ["dog toy", "toy", "do choi"],
    "do choi cho meo": ["cat toy", "toy", "do choi"],
    "do choi": ["toy", "toys", "ball", "chew"],
    toy: ["do choi", "bong", "xuong nhai", "ball", "chew"],
    "cat toy": ["do choi cho meo"],
    "dog toy": ["do choi cho cho"],

    "phu kien": ["accessory", "accessories", "gear"],
    accessory: ["phu kien", "do dung"],

    "quan ao": ["clothes", "clothing", "apparel", "outfit"],
    clothes: ["quan ao", "trang phuc"],

    shampoo: ["sua tam", "tam", "ve sinh"],
    "sua tam": ["shampoo", "bath", "cleaning"],

    "dental care": ["cham soc rang mieng", "ve sinh rang mieng", "oral care"],
    "oral care": ["dental care", "cham soc rang mieng", "ve sinh rang mieng"],

    "giam gia": ["sale", "discount", "deal", "promotion"],
    "khuyen mai": ["sale", "discount", "promotion"],
    sale: ["giam gia", "khuyen mai", "discount", "deal"],
    discount: ["giam gia", "khuyen mai", "sale"],

    "meo ken an": ["cat picky eater", "cat food", "wet food"],
    "cho moc rang": ["dog teething", "chew toy", "dental treat"],
    "cho dang moc rang": ["dog teething", "chew toy", "dental treat"],
    "do choi phu hop cho cho": ["dog toy", "do choi cho cho", "dog toys"],
    "do choi cho cho nho": ["small dog toy", "dog toy", "toy for small dog"],
    "lam sach cho thu cung": ["cleaning", "shampoo", "wipes", "ve sinh"],
    "ve sinh cho thu cung": ["cleaning", "shampoo", "wipes", "lam sach"],
};

const KEEP_IN_PHRASES = new Set(["meo", "dog", "cat", "cun"]);

const STRONG_PHRASES = [
    "thuc an cho meo",
    "thuc an cho cho",
    "san pham cho cho",
    "san pham cho meo",
    "phu kien cho cho",
    "phu kien cho meo",
    "do an cho meo",
    "do an cho cho",
    "hat cho meo",
    "hat cho cho",
    "pate cho meo",
    "pate cho cho",
    "sua cho meo",
    "sua cho cho",
    "do choi cho meo",
    "do choi cho cho",
    "cat food",
    "dog food",
    "kitten milk",
    "puppy milk",
    "cat toy",
    "dog toy",
    "giam gia",
    "khuyen mai",
    "khong giam gia",
    "khong sale",
    "gia goc",
    "meo ken an",
    "cho moc rang",
    "cho dang moc rang",
    "do choi phu hop cho cho",
    "do choi cho cho nho",
    "lam sach cho thu cung",
    "ve sinh cho thu cung",
];
const SEMANTIC_INTENT_HINTS = [
    "phu hop",
    "nen chon",
    "goi y",
    "tot cho",
    "ken an",
    "nang dong",
    "lam sach",
    "moc rang",
    "de nhai",
    "de tieu",
];
const BROAD_BROWSE_HINTS = [
    "san pham",
    "shop co gi",
    "co gi",
    "mat hang",
    "do cho",
];
module.exports = {
    VI_STOPWORDS,
    EN_STOPWORDS,
    VI_DOMAIN_KEYWORDS,
    EN_DOMAIN_KEYWORDS,
    PET_TYPE_PATTERNS,
    PET_SIZE_KEYWORDS,
    PRODUCT_FORM_KEYWORDS,
    DISCOUNT_KEYWORDS,
    NON_DISCOUNT_KEYWORDS,
    DOMAIN_SYNONYMS,
    KEEP_IN_PHRASES,
    STRONG_PHRASES,
    SEMANTIC_INTENT_HINTS,
    BROAD_BROWSE_HINTS,
};
