"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("Equipments", [
      {
        modelNumber: "EQ001",
        type: "Máy đo huyết áp",
        manufacturer: "Omron",
        serialNumber: "SN123456",
        assetNumber: "AST1001",
        location: "Phòng khám A",
        frequency: 6,
        department: "Y tế",
        status: "active",
        userId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        modelNumber: "EQ002",
        type: "Máy đo nhiệt độ",
        manufacturer: "Microlife",
        serialNumber: "SN654321",
        assetNumber: "AST1002",
        location: "Kho thiết bị",
        frequency: 12,
        department: "Kho",
        status: "maintenance",
        userId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        modelNumber: "EQ003",
        type: "Tester",
        manufacturer: "MIT",
        serialNumber: "123weerr",
        assetNumber: "1232425rffsv",
        location: "Line 5",
        frequency: 12,
        department: "QA",
        status: "active",
        userId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        modelNumber: "EQ004",
        type: "Analyzer",
        manufacturer: "Fluke",
        serialNumber: "FLK98765",
        assetNumber: "AST2003",
        location: "Line 3",
        frequency: 6,
        department: "Production",
        status: "active",
        userId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        modelNumber: "EQ005",
        type: "Multimeter",
        manufacturer: "Keysight",
        serialNumber: "KY123456",
        assetNumber: "AST2004",
        location: "Line 2",
        frequency: 12,
        department: "Maintenance",
        status: "maintenance",
        userId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        modelNumber: "EQ006",
        type: "Oscilloscope",
        manufacturer: "Tektronix",
        serialNumber: "TK654321",
        assetNumber: "AST2005",
        location: "Line 1",
        frequency: 24,
        department: "R&D",
        status: "active",
        userId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        modelNumber: "EQ007",
        type: "Thermometer",
        manufacturer: "Micro Tesh",
        serialNumber: "MT112233",
        assetNumber: "AST2006",
        location: "Line 4",
        frequency: 12,
        department: "QA",
        status: "active",
        userId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Equipments", null, {});
  },
};
